### ISSUE TITLE
 Databases 

### ISSUE THREAD

**Issue by Gonzywow** [NoffearrDeathProjecT/DeathCore_6.x.x#1]
Please world.sql

**Comment by Noffearr** [comment]
Coming soon! I'm still trying to fix some more things like NPCs, Items and more details!

**Comment by Noffearr** [comment]
Soon I will post the databases!

**Comment by Noffearr** [comment]
Databases its Update

**Comment by Gonzywow** [comment]
Thank database! When will update Pandaria, Warlords of Draenor creature, quest npc

**Comment by Noffearr** [comment]
We are working on it yet! Because we have a great team only 02 members!
