### ISSUE TITLE
Still no good cmake

### ISSUE THREAD

**Issue by Gonzywow** [NoffearrDeathProjecT/DeathCore_6.x.x#2]
8%] Building CXX object src/tools/vmap4_extractor/CMakeFiles/vmap4extractor.dir/wmo.cpp.o
Linking CXX executable mapextractor
CMakeFiles/mapextractor.dir/System.cpp.o: In function `OpenCascStorage()':
System.cpp:(.text+0x6344): undefined reference to `boost::filesystem3::detail::current_path(boost::system::error_code*)'
System.cpp:(.text+0x6352): undefined reference to `boost::filesystem3::path::wchar_t_codecvt_facet()'
System.cpp:(.text+0x63a2): undefined reference to `boost::filesystem3::detail::canonical(boost::filesystem3::path const&, boost::filesystem3::path const&, boost::system::error_code*)'
System.cpp:(.text+0x63c0): undefined reference to `boost::filesystem3::path::operator/=(boost::filesystem3::path const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/tools/map_extractor/mapextractor] Error 1
make[1]: *** [src/tools/map_extractor/CMakeFiles/mapextractor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by Noffearr** [comment]
This is very strange because before making any update I test before, it may be that I'm not testing on Linux, but in Windowns, from now on I will do the tests on Linux too! Thank you for reporting errors! Will be working to secure it! Good job !!
